# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e5385d13242bc6d16cdf0dce29462a17c8a3a8f7478b654973dfcecffa71048ef23d34147c1d1e0ac0b417e20070a526403ccc02c4ca7ae9f63b051510c3159

test:
  secret_key_base: 4fff3c42f1ee0aaa75b222a4358f101254b3595921b27cae7fc0f9922b77b7ca5369d7875d0c8a0d7134e162eb7813106f23583454e45f3b9de51d9c8e668917

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
